USE recycling_manager_db;

-- Candidates
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (1, 'Natasha Crooks', 14, '["Conflict Resolution","Data Analysis","Lean Manufacturing","Team Leadership"]', 'net advocate  😑');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (2, 'Alexis Hackett', 6, '["Lean Manufacturing","Conflict Resolution","Waste Management"]', 'gamer');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (3, 'Rodney Fritsch', 13, '["Data Analysis","Lean Manufacturing","Supply Chain Optimization","Equipment Maintenance"]', 'uniform junkie');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (4, 'Marta Christiansen-Adams', 3, '["OSHA Safety","Sustainability Reporting","Supply Chain Optimization","Conflict Resolution","Data Analysis","Six Sigma"]', 'freezer junkie, dreamer ↖️');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (5, 'Orville Johns', 5, '["OSHA Safety","Supply Chain Optimization","Equipment Maintenance"]', 'student');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (6, 'Thelma Ortiz', 12, '["Supply Chain Optimization","Sustainability Reporting","Conflict Resolution","Lean Manufacturing","Team Leadership","Six Sigma"]', 'tiger lover');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (7, 'Malcolm Carter', 6, '["Data Analysis","Six Sigma","Sustainability Reporting","OSHA Safety"]', 'reputation advocate, entrepreneur 🌗');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (8, 'Wilfred Brekke', 12, '["OSHA Safety","Equipment Maintenance","Supply Chain Optimization","Conflict Resolution","Six Sigma"]', 'friend, filmmaker');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (9, 'Leroy Connelly', 16, '["Data Analysis","Sustainability Reporting","Lean Manufacturing"]', 'grief supporter, designer 💮');
INSERT INTO candidates (id, name, experience_years, skills, bio) VALUES (10, 'Grant Abernathy', 16, '["Sustainability Reporting","Supply Chain Optimization","Team Leadership","OSHA Safety","Equipment Maintenance","Lean Manufacturing"]', 'business owner');

-- Evaluations
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (1, 4, 3, 49, 'Natasha Crooks appears to be a seasoned production line manager with significant experience, but her scores suggest that she may have areas for improvement in leadership and sustainability-related aspects crucial for this Recycling Production Line Manager role.  However, considering her overall 14 years of experience and relevant skills such as Conflict Resolution, Data Analysis, Lean Manufacturing, and Team Leadership, she might be suitable for this position with targeted training and development in the areas that require improvement.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (2, 4, 9, 60, 'Alexis Hackett, with 6 years of experience and a strong foundation in Lean Manufacturing and Waste Management, appears to be a suitable candidate for the Recycling Production Line Manager role, but further development in crisis management skills and motivation is necessary to maximize their potential.   Below is a more detailed evaluation of the candidate based on the given information:  **Strengths:**  - 9/10 in Sustainability, demonstrating a strong understanding of environmentally responsible practices. - Experience in Lean Manufacturing, which can be beneficial in optimizing production processes and improving efficiency. - Skilled in Waste Management, crucial for a Recycling Production Line Manager. - 4 years of experience in the role may not be a lot, however, 6 years of experience in the industry shows a level of maturity and experience.  **Weaknesses:**  - A score of 4/10 in Crisis Management indicates a need for additional training and experience in handling unexpected situations. - A motivation score of 60/100 may indicate that Alexis struggles to stay motivated, which can negatively affect their performance in a management role.  **Recommendations:**  - Provide additional training on crisis management to help Alexis improve their skills in handling unexpected situations. - Offer support and resources to help Alexis improve their motivation and engagement in their role. - Consider onboarding Alexis under a more experienced Production Line Manager or providing mentorship to aid their growth in the role.  Overall, with targeted support and development, Alexis Hackett has the potential to excel as a Recycling Production Line Manager.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (3, 2, 3, 47, 'Based on Rodney Fritsch''s provided experience and skills, I would say that he is a suitable candidate for the Recycling Production Line Manager role, as he has extensive experience and skills in areas like Lean Manufacturing, Supply Chain Optimization, and Equipment Maintenance, but requires further development in Crisis Management, Sustainability, and Motivation.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (4, 3, 5, 60, 'Marta Christiansen-Adams appears to be a potentially suitable candidate for a Recycling Production Line Manager role due to her relevant skills and experience, although additional training or development to improve crisis management and leadership skills may be necessary.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (5, 10, 5, 44, 'Orville Johns appears to be a suitable candidate for a Recycling Production Line Manager role, with exceptional crisis management skills and expertise in OSHA safety and supply chain optimization, albeit with room for improvement in sustainability and employee motivation.  Here''s a more detailed evaluation:  Strengths:  1. **Crisis Management**: Orville''s high score in crisis management suggests he can effectively handle emergencies and unexpected events on the production line, minimizing downtime and ensuring smooth operations. 2. **Safety Expertise**: His OSHA safety certification demonstrates his knowledge of workplace safety protocols, which is essential for a production line manager. 3. **Supply Chain Optimization**: His skills in supply chain optimization can help reduce waste, improve production efficiency, and enhance the overall profitability of the recycling operation.  Weaknesses:  1. **Sustainability Knowledge**: Orville''s relatively low score in sustainability indicates a need for training or further education on sustainable practices, such as reducing waste, conserving resources, and implementing environmentally friendly technologies. 2. **Motivation and Employee Engagement**: His score in motivation is concerning, as a production line manager must inspire and lead a team to achieve production goals. He may need to work on building trust, recognizing individual contributions, and creating a positive work environment.  Recommendations:  1. Provide training or education on sustainable practices and environmental management systems to enhance Orville''s sustainability knowledge. 2. Develop a plan to improve his motivation and employee engagement skills through workshops, coaching, or mentoring. 3. Monitor his performance closely to ensure his strengths are leveraged and his weaknesses addressed.  Overall, Orville''s exceptional crisis management and safety expertise make him a solid candidate for the Recycling Production Line Manager role, with potential for growth and development in sustainability and employee motivation.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (6, 7, 5, 68, 'Thelma Ortiz is a seasoned recycling production line manager with strong skills in supply chain optimization, lean manufacturing, and team leadership, making her a suitable candidate for this role.   To evaluate the candidate more thoroughly:  - **Strengths:**   - 12 years of experience as a recycling production line manager, which demonstrates her extensive knowledge and practical application of recycling production methods.   - Proficiency in Supply Chain Optimization, Lean Manufacturing, and Team Leadership can help optimize workflows, reduce waste, and improve team efficiency.   - Her Six Sigma certification indicates her ability to identify and address process inefficiencies.  - **Weaknesses:**   - Crisis Management skills, though somewhat developed, need improvement, as evidenced by a lower score (7/10).   - Her score in Sustainability is lower than expected (5/10), suggesting she may require additional training or experience in this area.  - **Average rating:** 6.7/10 - **Recommendation:** Provide additional training and support to enhance her crisis management and sustainability skills to complement her existing expertise. - **Conclusion**: Thelma Ortiz, despite some areas for improvement, shows a lot of potential as a recycling production line manager with her extensive experience and diverse skill set.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (7, 1, 7, 75, 'Malcolm Carter is a candidate with potential, but his limited crisis management skills raise concerns about his ability to effectively manage a Recycling Production Line, where emergency situations can arise.  Here''s a breakdown of his strengths and weaknesses:  Strengths:  - 6 years of experience in the recycling industry - Strong data analysis skills, which are essential for identifying areas of improvement - Knowledge of Six Sigma methodologies to optimize production processes - Familiarity with OSHA safety guidelines to ensure worker well-being - Good understanding of sustainability reporting, which is crucial for a recycling production line  Weaknesses:  - Low score in crisis management, which may hinder his ability to respond effectively in emergency situations - Moderate score in sustainability (7/10), which suggests room for improvement in this area - Slightly below-average score in motivation (75/100), which may indicate a need to boost his enthusiasm and engagement  Considering these factors, it''s essential to assess whether Malcolm''s strengths outweigh his weaknesses and if he can be further developed to excel in this role.  Recommendations for further evaluation:  - Schedule an interview with Malcolm to discuss his crisis management approach and experience - Review his sustainability reporting skills and provide guidance for improvement - Explore opportunities to boost his motivation and engagement, possibly through training or mentoring - Conduct a skills assessment to determine if additional training is necessary in areas like crisis management and sustainability');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (8, 8, 1, 99, 'Wilfred Brekke is a highly experienced and skilled candidate with 99% motivation, a strong background in equipment maintenance and supply chain optimization, showing potential for the Recycling Production Line Manager role, but may require additional education or training to significantly enhance sustainability efforts.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (9, 7, 10, 75, 'Leroy Connelly is a seasoned candidate with 16 years of experience, demonstrating strong skills in data analysis and sustainability, but requires further development in motivation and crisis management to excel as a Recycling Production Line Manager.  Key strengths: - 16 years of experience in the field, suggesting expertise and depth of knowledge. - High score in sustainability (10/10), indicating a strong understanding of environmental responsibility. - Proficiency in data analysis, which is crucial for a production line manager.  Areas for improvement: - Crisis management (7/10) is a concern, as it may indicate difficulties in high-pressure situations. - Lower motivation score (75/100) suggests that Leroy may need additional support to drive performance and maintain energy levels.  Recommendation: Leroy Connelly is a viable candidate for the Recycling Production Line Manager role, but requires additional training or mentorship to enhance his crisis management skills and motivation. His extensive experience and strong sustainability background make him an attractive option, but careful consideration should be given to addressing these areas of improvement.');
INSERT INTO evaluations (candidate_id, crisis_score, sustainability_score, motivation_score, ai_feedback) VALUES (10, 5, 8, 53, 'Grant Abernathy, a 16-year industry veteran with strengths in leadership, sustainability, and supply chain optimization, is a suitable candidate for a Recycling Production Line Manager role, though areas such as crisis management and motivation may require additional development.');

-- Rankings
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (9, 81, 1);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (8, 66.6, 2);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (6, 63.2, 3);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (2, 63, 4);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (5, 62.6, 5);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (10, 60.2, 6);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (7, 54, 7);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (4, 48, 8);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (1, 40.6, 9);
INSERT INTO rankings (candidate_id, total_score, rank_position) VALUES (3, 33.8, 10);
