import { faker } from '@faker-js/faker';

// pool of high-quality AI feedback generated by Llama 3.1 8b Instant
const aiFeedbackPool = [
  "This candidate appears to be a seasoned production line manager with significant experience, but scores suggest areas for improvement in leadership and sustainability-related aspects.",
  "With a strong foundation in Lean Manufacturing and Waste Management, they appear to be a suitable candidate, but further development in crisis management skills and motivation is necessary.",
  "Based on provided experience and skills, they are a suitable candidate for the role, having extensive experience but requiring further development in Crisis Management, Sustainability, and Motivation.",
  "Appears to be a potentially suitable candidate due to relevant skills and experience, although additional training or development to improve crisis management and leadership skills may be necessary.",
  "A suitable candidate with exceptional crisis management skills and expertise in OSHA safety, albeit with room for improvement in sustainability and employee motivation.",
  "A seasoned manager with strong skills in supply chain optimization, lean manufacturing, and team leadership, making them a suitable candidate for this role despite lower crisis management scores.",
  "A candidate with potential, but limited crisis management skills raise concerns about ability to effectively manage a production line where emergency situations can arise.",
  "Highly experienced and skilled with very high motivation, a strong background in equipment maintenance and supply chain optimization, showing great potential.",
  "Seasoned candidate with strong skills in data analysis and sustainability, but requires further development in motivation and crisis management to excel.",
  "An industry veteran with strengths in leadership, sustainability, and supply chain optimization, suitable for the role though crisis management may require development."
];

const skillsList = [
  'Lean Manufacturing', 'Six Sigma', 'OSHA Safety', 'Waste Management',
  'Team Leadership', 'Conflict Resolution', 'Supply Chain Optimization',
  'Sustainability Reporting', 'Equipment Maintenance', 'Data Analysis'
];

export const generateCandidates = (count = 40) => {
  const rankings = [];

  for (let i = 1; i <= count; i++) {
    const candidate = {
      id: i,
      name: faker.person.fullName(),
      experience_years: faker.number.int({ min: 2, max: 20 }),
      bio: faker.person.bio(),
      avatar: faker.image.avatar()
    };

    const numSkills = faker.number.int({ min: 3, max: 6 });
    candidate.skills = faker.helpers.arrayElements(skillsList, numSkills);

    const crisis_score = faker.number.int({ min: 1, max: 10 });
    const sustainability_score = faker.number.int({ min: 1, max: 10 });
    const motivation_score = faker.number.int({ min: 40, max: 100 });
    const ai_feedback = faker.helpers.arrayElement(aiFeedbackPool);

    const totalScore = (
        (crisis_score * 3) + 
        (sustainability_score * 3) + 
        (motivation_score * 0.4)
    ).toFixed(2);

    rankings.push({
        ...candidate,
        candidate_id: i,
        total_score: parseFloat(totalScore),
        rank: 0,
        crisis_score,
        sustainability_score,
        motivation_score,
        ai_feedback,
    });
  }

  rankings.sort((a, b) => b.total_score - a.total_score);
  rankings.forEach((r, index) => r.rank = index + 1);

  return rankings;
};
